<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Employee extends Model
{
    protected $table = 'employee';
    protected $primaryKey = 'id';
    public $incrementing = true;
    protected $connection = 'mysql';
    protected $fillable = ['name'];

    public static function all($columns = ['*'])
    {
        return static::query()->get(
            is_array($columns) ? $columns : func_get_args()
        );
    }

    public static function getEmployeesByIdCompany($idCompany, $columns = ['*'])
    {
        return static::query()
            ->where('idCompany', $idCompany)
            ->orderBy('id', 'desc')
            ->take(10)
            ->get(
                is_array($columns) ? $columns : func_get_args()
            );
    }

    public function newInstance($attributes = [], $exists = false)
    {
        return parent::newInstance($attributes, $exists); // TODO: Change the autogenerated stub
    }


}
